/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wang_demo_jni_JniTest */

#ifndef _Included_wang_demo_root_jnitest_JniTest
#define _Included_wang_demo_root_jnitest_JniTest
#define LOG_TAG "Mp3Encoding"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wang_demo_jni_JniTest
 * Method:    hello
 * Signature: ()V
 */
jstring Java_wang_demo_root_jnitest_JniTest_hello(JNIEnv *env,jclass thiz){

    return (*env)->NewStringUTF(env,"SUCCESS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
}

#ifdef __cplusplus
}
#endif
#endif
